#!/usr/bin/env bash
# Takes in 2 arguments and outputs the subdomain and its destination

func ()
{
	doms=$(dig "$2.$1" | grep -A1 "ANSWER SECTION:" | tail -1)
	echo "$2 $doms" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ "$#" -eq 1 ]
then
	func "$1" "www"
	func "$1" "lb-01"
	func "$1" "web-01"
	func "$1" "web-02"
elif [ "$#" -eq 2 ]
then
	func "$1" "$2"
fi
