#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive
# Geting password from command-line argument
MYSQL_PASSWORD="$1"

# Specifying filename format for the backup
FILE_NAME="$(date +"%d-%m-%Y").tar.gz"

# Dumping and compressing the MySQL databases
mysqldump --user=root --password="$MYSQL_PASSWORD" --all-databases > backup.sql
tar -czf "$FILE_NAME" "backup.sql"
