#!/usr/bin/env bash
#  Bash script that gives you information about the "school" file.

file="school"

if [ -e "$file" ]; then
  echo "$file exists"

  if [ -f "$file" ]; then
    echo "$file is a regular file"
    if [ -s "$file" ]; then
      echo "$file file is not empty"
    else
      echo "$file file is empty"
    fi
  else
    echo "$file exists but it's a directory"
  fi
else
  echo "$file does not exist"
fi
